---
- hosts: all
  gather_facts: no
  vars_files:
  - dot_file.yml
  - apt.yml
  tasks:
  - include: tasks/sync_dot_files.yml
    tags: [sync-dot-files]
  - include: tasks/add_dot_file.yml
    tags: [add-dot-file]
  - include: tasks/remove_dot_files.yml
    tags: [remove-dot-files]
  - include: tasks/sync_apt_packages.yml
    tags: [sync-apt-packages]
  - include: tasks/install_apt_package.yml
    tags: [install-apt-package]