---
- hosts: all
  gather_facts: no
  vars_files:
  - dot_file.yml
  - config_file.yml
  - apt.yml
  - yum.yml
  - brew.yml
  - cask.yml
  - yay.yml
  tasks:
  - include: tasks/sync_dot_files.yml
    tags: [sync-dot-files]
  - include: tasks/add_dot_file.yml
    tags: [add-dot-file]
  - include: tasks/remove_dot_files.yml
    tags: [remove-dot-files]
  - include: tasks/sync_config_files.yml
    tags: [sync-config-files]
  - include: tasks/add_config_file.yml
    tags: [add-config-file]
  - include: tasks/remove_config_files.yml
    tags: [remove-config-files]
  - include: tasks/sync_apt_packages.yml
    tags: [sync-apt-packages]
  - include: tasks/install_apt_package.yml
    tags: [install-apt-package]
  - include: tasks/sync_yum_packages.yml
    tags: [sync-yum-packages]
  - include: tasks/install_yum_package.yml
    tags: [install-yum-package]
  - include: tasks/sync_brew_packages.yml
    tags: [sync-brew-packages]
  - include: tasks/install_brew_package.yml
    tags: [install-brew-package]
  - include: tasks/sync_cask_packages.yml
    tags: [sync-cask-packages]
  - include: tasks/install_cask_package.yml
    tags: [install-cask-package]
  - include: tasks/sync_yay_packages.yml
    tags: [sync-yay-packages]
  - include: tasks/install_yay_package.yml
    tags: [install-yay-package]
