---
- name: Move config dir
  command: "mv ~/.config/{{config}} {{playbook_dir}}/src"
  with_first_found:
  - files: "~/.config/{{config}}"
- name: Create symlink configfile
  file:
    src: "{{playbook_dir}}/src/{{config}}"
    dest: "~/.config/{{config}}"
    state: link
- name: Update config list
  lineinfile:
    dest: ./config_file.yml
    line: "- {{config}}"
- name: Git commit dotfile
  shell: "git add config_file.yml {{playbook_dir}}/src/{{config}} && git commit -m 'Add {{config}}'"
