---
- name: Move dotfile
  command: "mv ~/.{{dotfile}} {{playbook_dir}}/src"
  with_first_found:
  - files: "~/.{{dotfile}}"
- name: Rename dotfile
  command: "mv .{{dotfile}} {{dotfile}}"
  args:
    chdir: ./src/
- name: Create symlink dotfile
  file:
    src: "{{playbook_dir}}/src/{{dotfile}}"
    dest: "~/.{{dotfile}}"
    state: link
- name: Update dotfile list
  lineinfile:
    dest: ./dot_file.yml
    line: "- {{dotfile}}"
- name: Git commit dotfile
  shell: "git add dot_file.yml {{playbook_dir}}/src/{{dotfile}} && git commit -m 'Add {{dotfile}}'"